[build]
  # Base directory é apenas a pasta client
  base = "client"
  
  # Comando de build para o frontend
  command = "npm run build"
  
  # Pasta de publicação
  publish = "dist/spa"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 