[build]
  # Base directory é a raiz do projeto
  base = "."
  
  # Comando de build correto
  command = "npm run build:client"
  
  # Pasta de publicação
  publish = "client/dist/spa"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 