import React from 'react';
import { NewZKSystemTestComponent } from '../zk-proof-api/components/NewZKSystemTest';
import { Logo } from '../components/Logo';

export const NewZKSystemTestPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <Logo className="mx-auto mb-4" />
          <h1 className="text-3xl font-bold text-foreground mb-2">
            🧪 New ZK System Test
          </h1>
          <p className="text-lg text-foreground/80">
            Independent system using artifacts generated by the API
          </p>
        </div>

        {/* Info Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <div className="bg-card border border-border p-6 rounded-lg shadow-md">
            <div className="text-2xl mb-2">🔧</div>
            <h3 className="font-semibold text-foreground mb-2">Build API</h3>
            <p className="text-foreground/70 text-sm">
              Circuits compiled in real-time using Circom and SnarkJS
            </p>
          </div>
          
          <div className="bg-card border border-border p-6 rounded-lg shadow-md">
            <div className="text-2xl mb-2">📦</div>
            <h3 className="font-semibold text-foreground mb-2">Base64 Artifacts</h3>
            <p className="text-foreground/70 text-sm">
              WASM, ZKEY and VKEY converted for client-side use
            </p>
          </div>
          
          <div className="bg-card border border-border p-6 rounded-lg shadow-md">
            <div className="text-2xl mb-2">🔗</div>
            <h3 className="font-semibold text-foreground mb-2">ZKVerify Integration</h3>
            <p className="text-foreground/70 text-sm">
              Direct submission to blockchain with Subwallet
            </p>
          </div>
        </div>

        {/* Warning */}
        <div className="bg-yellow-950/20 border border-yellow-500/30 rounded-lg p-4 mb-8">
          <div className="flex">
            <div className="text-yellow-400 text-xl mr-3">⚠️</div>
            <div>
              <h3 className="font-semibold text-yellow-400">Independent Test</h3>
              <p className="text-yellow-300 text-sm">
                This test uses the new independent ZK system separate from the current MVP. 
                If it works, we will replace the old system with the new one.
              </p>
            </div>
          </div>
        </div>

        {/* Test Component */}
        <NewZKSystemTestComponent />

        {/* Footer */}
        <div className="mt-12 text-center text-foreground/70 text-sm">
          <p>
            ZK Test System - Automatically generated by the Build API
          </p>
        </div>
      </div>
    </div>
  );
}; 