import React from 'react';
import { NewZKSystemTestComponent } from '../zk-proof-api/components/NewZKSystemTest';
import { Logo } from '../components/Logo';
import { Button } from '../components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Breadcrumb } from '../components/ui/breadcrumb';

export const NewZKSystemTestPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-background text-foreground relative overflow-hidden">
      {/* Background gradient blur effect - same as other pages */}
      <div
        className="absolute inset-0 opacity-30"
        style={{
          background:
            "radial-gradient(50.1% 88.38% at 46.22% 80.46%, #004EF6 0%, #002168 70.19%, #00022A 87.98%)",
          filter: "blur(120px)",
        }}
      />

      <div className="relative z-10">
        {/* Header - similar to other pages */}
        <header className="bg-card/50 px-4 lg:px-6 py-3 lg:py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link to="/login">
                <Button variant="ghost" size="sm" className="text-xs sm:text-sm">
                  <ArrowLeft className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" />
                  Back
                </Button>
              </Link>
            </div>
            <div className="flex items-center gap-2">
              <Logo size="md" className="h-8 w-auto" />
            </div>
          </div>
        </header>

        {/* Main Content */}
        <main className="p-4 lg:p-6">
          <Breadcrumb
            items={[
              { label: "Home", href: "/login" },
              { label: "New ZK System Test" },
            ]}
          />

          <div className="mt-6 lg:mt-8 max-w-4xl mx-auto">
            {/* Header Section */}
            <div className="text-center mb-8 lg:mb-12">
              <h1 className="text-2xl lg:text-4xl font-bold text-foreground mb-4">
                🧪 New ZK System Test
              </h1>
              <p className="text-lg text-foreground/80 mb-6 lg:mb-8 max-w-2xl mx-auto">
                Independent system using artifacts generated by the API
              </p>
            </div>

            {/* Info Cards */}
            <div className="grid md:grid-cols-3 gap-6 mb-8">
              <div className="bg-card/50 border border-border/50 p-6 rounded-lg shadow-md">
                <div className="text-2xl mb-2">🔧</div>
                <h3 className="font-semibold text-foreground mb-2">Build API</h3>
                <p className="text-foreground/70 text-sm">
                  Circuits compiled in real-time using Circom and SnarkJS
                </p>
              </div>
              
              <div className="bg-card/50 border border-border/50 p-6 rounded-lg shadow-md">
                <div className="text-2xl mb-2">📦</div>
                <h3 className="font-semibold text-foreground mb-2">Base64 Artifacts</h3>
                <p className="text-foreground/70 text-sm">
                  WASM, ZKEY and VKEY converted for client-side use
                </p>
              </div>
              
              <div className="bg-card/50 border border-border/50 p-6 rounded-lg shadow-md">
                <div className="text-2xl mb-2">🔗</div>
                <h3 className="font-semibold text-foreground mb-2">ZKVerify Integration</h3>
                <p className="text-foreground/70 text-sm">
                  Direct submission to blockchain with Subwallet
                </p>
              </div>
            </div>

            {/* Warning */}
            <div className="bg-yellow-950/20 border border-yellow-500/30 rounded-lg p-4 mb-8">
              <div className="flex">
                <div className="text-yellow-400 text-xl mr-3">⚠️</div>
                <div>
                  <h3 className="font-semibold text-yellow-400">Independent Test</h3>
                  <p className="text-yellow-300 text-sm">
                    This test uses the new independent ZK system separate from the current MVP. 
                    If it works, we will replace the old system with the new one.
                  </p>
                </div>
              </div>
            </div>

            {/* Test Component */}
            <NewZKSystemTestComponent />

            {/* Footer */}
            <div className="mt-12 text-center text-foreground/70 text-sm">
              <p>
                ZK Test System - Automatically generated by the Build API
              </p>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}; 