import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

// Translations
const translations = {
  pt: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.lances': 'Lances',
    'nav.wallet': 'Carteira',
    'nav.settings': 'Configurações',
    'nav.support': 'Suporte',
    'nav.ranking': 'Ranking',
    'nav.investments': 'Investimentos',
    'nav.contributions': 'Contribuições',
    'nav.deposit': 'Depositar',
    'nav.withdraw': 'Sacar',
    'nav.admin': 'Admin',
    
    // Authentication
    'auth.login': 'Login',
    'auth.register': 'Cadastrar',
    'auth.logout': 'Sair',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.fullName': 'Nome Completo',
    'auth.forgotPassword': 'Esqueci minha Senha',
    'auth.alreadyHaveAccount': 'Já tem uma conta?',
    'auth.dontHaveAccount': 'Não tem uma conta?',
    'auth.enter': 'Entrar',
    'auth.entering': 'Entrando...',
    'auth.registering': 'Cadastrando...',
    'auth.walletConnected': 'Carteira conectada',
    'auth.or': 'ou',
    'auth.comingSoon': 'Em breve',
    
    // User
    'user.welcome': 'Que bom ter você aqui',
    'user.howToUse': 'Como você gostaria de utilizar a ZK Finance?',
    'user.wantCredit': 'Quero um empréstimo para o meu negócio',
    'user.wantInvest': 'Quero Investir',
    'user.user': 'Usuário',
    'user.investor': 'Investidor',
    'investor.contributions.title': 'Lances Contribuídos',
    'investor.contributions.subtitle': 'Acompanhe seus investimentos e retornos em tempo real',
    'user.borrower': 'Tomador',
    
    // Dashboard
    'dashboard.welcome': 'Olá',
    'dashboard.noBalance': 'Você ainda não possui um Saldo ativo',
    'dashboard.createNewLance': 'Criar novo lance',
    'dashboard.myLances': 'Meus Lances',
    'dashboard.createLance': 'Criar Lance',
    'dashboard.filter': 'Filtrar',
    'dashboard.zkScore': 'ZK Score',
    'dashboard.postedLances': 'Lances Postados',
    'dashboard.totalRaised': 'Total Arrecadado',
    'dashboard.securedCredit': 'Crédito Assegurado até a Data',
    'dashboard.goal': 'Meta',
    'dashboard.progress': 'Progresso',
    'dashboard.currentAmount': 'Crédito Assegurado Atual',
    'dashboard.collaterals': 'Colaterais Cadastrados',
    'dashboard.registerCollateral': 'Cadastrar Colateral',
    'dashboard.totalValue': 'Valor Total',
    'dashboard.seeLanceDetails': 'ver detalhes do lance',
    'dashboard.requestCredit': 'Solicitar Crédito',
    'dashboard.title': 'Dashboard',
    'dashboard.ranking': 'Ranking',
    'dashboard.lances': 'Lances',
    'dashboard.investmentPerformance': 'Performance de Investimentos',
    'dashboard.recentActivities': 'Atividades Recentes',
    'dashboard.noRecentActivity': 'Nenhuma atividade recente',
    'dashboard.averageAPY': 'APY Médio Total',
    'dashboard.totalInvested': 'Total Investido',
    'dashboard.totalReturn': 'Total Retorno',
    'dashboard.viewInvestmentDetails': 'Ver Detalhes dos Investimentos',
    'dashboard.invested': 'Investido',
    'dashboard.return': 'Retorno',
    'dashboard.last7Days': 'Últimos 7 dias',
    'dashboard.deposit': 'Depositar',
    'dashboard.withdraw': 'Sacar',
    'dashboard.contributions': 'Contribuições',
    'dashboard.approved': 'Aprovada',
    'dashboard.inAnalysis': 'Em Análise',
    'dashboard.notAuthorized': 'Não Autorizada',
    'dashboard.backToKYC': 'Voltar ao KYC',
    'dashboard.support': 'Suporte',
    'dashboard.search': 'Buscar',
    'dashboard.level1': 'Nível 1',
    'dashboard.viewAchievements': 'Ver conquistas',
    'dashboard.securedCreditToDate': 'Crédito Assegurado até a Data',
    'dashboard.progressGoal': 'Progresso da Meta de Aporte Total',
    'dashboard.currentSecuredCredit': 'Crédito Assegurado Atual',
    'dashboard.value': 'Valor',
    'dashboard.interest': 'Interesse',
    'dashboard.expiresIn': 'Expira em',
    'dashboard.objective': 'Objetivo',
    
    // Carteira
    'wallet.title': 'Carteira',
    'wallet.balance': 'Saldo',
    'wallet.debtBalance': 'Saldo Devedor',
    'wallet.totalOutstanding': 'Valor total em aberto',
    'wallet.updatedToday': 'Atualizado hoje',
    'wallet.paymentTerm': 'Prazo de Pagamento',
    'wallet.remainingTime': 'Tempo restante',
    'wallet.monthsRemaining': 'meses restantes',
    'wallet.nextDue': 'Próximo Vencimento',
    'wallet.nextInstallment': 'Próxima parcela',
    'wallet.creditors': 'Credores',
    'wallet.settlementAndTotals': 'Quitação e Totais',
    'wallet.immediateSettlement': 'Quitação Imediata',
    'wallet.settleAllDebt': 'Valor para quitar todo o débito hoje',
    'wallet.totalFinal': 'Total Final',
    'wallet.totalAfterInterest': 'Montante total após juros no final do contrato',
    'wallet.settlementSavings': 'Economia na Quitação',
    'wallet.difference': 'Diferença entre quitação imediata e total final',
    'wallet.requestStatement': 'Solicitar Extrato',
    'wallet.negotiateSettlement': 'Negociar Quitação',
    'wallet.connect': 'Conectar Carteira',
    'wallet.connected': 'Carteira Conectada',
    'wallet.disconnect': 'Desconectar',
    'wallet.switchNetwork': 'Trocar Rede',
    'wallet.wrongNetwork': 'Rede Incorreta',
    'wallet.unsupportedNetwork': 'Rede Não Suportada',
    'wallet.connectWallet': 'Conectar Carteira',
    'wallet.noWallet': 'Nenhuma Carteira Encontrada',
    'wallet.installWallet': 'Instalar Carteira',
    'wallet.polkadot': 'Polkadot',
    'wallet.volta': 'Volta',
    'wallet.evm': 'EVM',
    'wallet.substrate': 'Substrate',
    'wallet.switchToPolkadot': 'Trocar para Polkadot',
    'wallet.switchToEVM': 'Trocar para EVM',
    'wallet.switchNetworks': 'Mudar Redes',
    'wallet.switching': 'Trocando...',
    'wallet.sepolia': 'Sepolia',
    'wallet.sepoliaDescription': 'Contrato de Loans EVM',
    'wallet.voltaDescription': 'Provas ZK ZKVerify',
    'wallet.limited': 'Limitado',
    'wallet.copyAddress': 'Copiar endereço',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.profile': 'Perfil',
    'settings.security': 'Segurança',
    'settings.notifications': 'Notificações',
    'settings.appearance': 'Aparência',
    'settings.saveChanges': 'Salvar Alterações',
    'settings.changePassword': 'Alterar Senha',
    'settings.currentPassword': 'Senha Atual',
    'settings.newPassword': 'Nova Senha',
    'settings.emailNotifications': 'Notificações por Email',
    'settings.emailUpdates': 'Receber atualizações por email',
    'settings.smsNotifications': 'Notificações por SMS',
    'settings.smsAlerts': 'Receber alertas por SMS',
    'settings.pushNotifications': 'Notificações Push',
    'settings.browserNotifications': 'Receber notificações no navegador',
    'settings.marketing': 'Marketing',
    'settings.offersAndNews': 'Receber ofertas e novidades',
    'settings.darkTheme': 'Tema Escuro',
    'settings.toggleTheme': 'Alternar entre tema claro e escuro',
    
    // Suporte
    'support.title': 'Suporte',
    'support.howCanWeHelp': 'Como podemos ajudar?',
    'support.findAnswers': 'Encontre respostas rápidas para suas dúvidas ou entre em contato com nossa equipe de suporte especializada.',
    'support.phone': 'Telefone',
    'support.24hService': 'Atendimento 24/7',
    'support.callNow': 'Ligar agora',
    'support.email': 'Email',
    'support.response2h': 'Resposta em até 2h',
    'support.sendEmail': 'Enviar email',
    'support.chat': 'Chat',
    'support.onlineService': 'Atendimento online',
    'support.availableNow': 'Disponível agora',
    'support.startChat': 'Iniciar chat',
    'support.faq': 'Perguntas Frequentes',
    'support.searchFaq': 'Buscar nas perguntas frequentes...',
    'support.usefulResources': 'Recursos Úteis',
    'support.userGuide': 'Guia do Usuário',
    'support.completeTutorial': 'Tutorial completo da plataforma',
    'support.videoTutorials': 'Vídeos Tutoriais',
    'support.learnWithVideos': 'Aprenda com vídeos explicativos',
    'support.termsOfUse': 'Termos de Uso',
    'support.platformPolicies': 'Políticas e condições da plataforma',
    'support.mobileApp': 'Aplicativo Mobile',
    'support.downloadApp': 'Baixe nosso app para Android e iOS',
    'support.access': 'Acessar',
    'support.subject': 'Assunto',
    'support.enterSubject': 'Digite o assunto da sua mensagem',
    'support.message': 'Mensagem',
    'support.describeIssue': 'Descreva sua dúvida ou problema...',
    'support.phoneOptional': 'Telefone (opcional)',
    
    // KYC
    'kyc.title': 'Solicitação de Crédito',
    'kyc.personalInfo': 'Informações Pessoais',
    'kyc.idVerification': 'Verificação ID',
    'kyc.selfie': 'Selfie',
    'kyc.review': 'Review',
    'kyc.creditData': 'Dados de Crédito',
    'kyc.generalInfo': 'Informações Gerais',
    'kyc.scanCollateral': 'Scanear Garantia',
    'kyc.analysis': 'Análise',
    'kyc.step': 'Passo',
    'kyc.fillPersonalInfo': 'Preencha os espaços com suas informações pessoais',
    'kyc.uploadDocuments': 'Faça upload dos documentos de identificação',
    'kyc.takeSelfie': 'Tire uma selfie para verificação facial',
    'kyc.reviewInfo': 'Revise todas as informações antes de prosseguir',
    'kyc.financialData': 'Informe seus dados financeiros e de crédito',
    'kyc.scanAssets': 'Escaneie ou fotografe seus bens como garantia',
    'kyc.zkProcessing': 'Processamento ZK e geração de score de crédito',
    'kyc.fullName': 'Nome completo',
    'kyc.birthDate': 'Data de nascimento',
    'kyc.state': 'Estado',
    'kyc.city': 'Cidade',
    'kyc.address': 'Endereço',
    'kyc.number': 'Número',
    'kyc.documentUpload': 'Upload de Documentos',
    'kyc.uploadFollowing': 'Faça upload dos seguintes documentos:',
    'kyc.rgOrCnh': 'RG ou CNH (frente e verso)',
    'kyc.residenceProof': 'Comprovante de residência',
    'kyc.selectFiles': 'Selecionar Arquivos',
    'kyc.facialVerification': 'Verificação Facial',
    'kyc.takeSelfieForVerification': 'Tire uma selfie para verificação de identidade',
    'kyc.infoReview': 'Revisão das Informações',
    'kyc.notInformed': 'Não informado',
    'kyc.documentsSent': 'Documentos enviados',
    'kyc.selfieCaptured': 'Selfie capturada',
    'kyc.infoVerified': 'Informações verificadas',
    'kyc.monthlyIncome': 'Renda mensal',
    'kyc.profession': 'Profissão',
    'kyc.company': 'Empresa',
    'kyc.phone': 'Telefone',
    'kyc.collateralsAndGuarantees': 'Garantias e Colaterais',
    'kyc.scanOrPhoto': 'Escaneie ou fotografe seus bens como garantia:',
    'kyc.vehicles': 'Veículos',
    'kyc.properties': 'Imóveis',
    'kyc.electronics': 'Eletrônicos',
    'kyc.otherValuableAssets': 'Outros bens de valor',
    'kyc.scanGuarantees': 'Escanear Garantias',
    'kyc.zkAnalysisInProgress': 'Análise com Prova ZK em Andamento',
    'kyc.processingData': 'Estamos processando seus dados através de nossa tecnologia ZK Finance. Este processo pode levar até 24 horas.',
    'kyc.zkCreditScoreProof': 'Prova ZK de Score de Crédito',
    'kyc.financialDataProcessed': 'Seus dados financeiros e pessoais são processados por algoritmos de IA sem serem armazenados. Apenas o score final é gerado através de prova zero-knowledge, garantindo total privacidade.',
    'kyc.privacyGuaranteed': 'Privacidade Garantida',
    'kyc.personalDataNotStored': 'Dados pessoais não são armazenados',
    'kyc.processingViaZk': 'Processamento via algoritmo ZK',
    'kyc.scoreGeneratedByAi': 'Score gerado por IA sem retenção de dados',
    'kyc.lgpdCompliance': 'Conformidade com LGPD',
    'kyc.processingZkProof': 'Processando prova ZK...',
    'kyc.previous': 'Anterior',
    'kyc.next': 'Próximo',
    'kyc.finish': 'Finalizar',
    'kyc.backToKyc': 'Voltar ao KYC',
    'kyc.verification': 'KYC Verificação',
    
    // Geral
    'common.back': 'Voltar',
    'common.backToDashboard': 'Voltar ao Dashboard',
    'common.home': 'Início',
    'common.search': 'Buscar',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    'common.info': 'Informação',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.view': 'Visualizar',
    'common.add': 'Adicionar',
    'common.remove': 'Remover',
    'common.close': 'Fechar',
    'common.open': 'Abrir',
    'common.submit': 'Enviar',
    'common.reset': 'Limpar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.date': 'Data',
    'common.time': 'Hora',
    'common.amount': 'Valor',
    'common.total': 'Total',
    'common.status': 'Status',
    'common.active': 'Ativo',
    'common.inactive': 'Inativo',
    'common.pending': 'Pendente',
    'common.completed': 'Concluído',
    'common.failed': 'Falhou',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.connected': 'Conectado',
    'common.disconnected': 'Desconectado',
    'common.ready': 'Pronto',
    'common.busy': 'Ocupado',
    'common.working': 'Trabalhando',
    'common.done': 'Concluído',
    'common.waiting': 'Aguardando',
    'common.processing': 'Processando',
    'common.available': 'Disponível',
    'common.unavailable': 'Indisponível',
    'common.enabled': 'Habilitado',
    'common.disabled': 'Desabilitado',
    'common.on': 'Ligado',
    'common.off': 'Desligado',
    'common.true': 'Verdadeiro',
    'common.false': 'Falso',
    'common.high': 'Alto',
    'common.low': 'Baixo',
    'common.medium': 'Médio',
    'common.small': 'Pequeno',
    'common.large': 'Grande',
    'common.new': 'Novo',
    'common.old': 'Antigo',
    'common.recent': 'Recente',
    'common.latest': 'Mais recente',
    'common.first': 'Primeiro',
    'common.last': 'Último',
    'common.best': 'Melhor',
    'common.worst': 'Pior',
    'common.good': 'Bom',
    'common.bad': 'Ruim',
    'common.maximum': 'Máximo',
    'common.minimum': 'Mínimo',
    'common.average': 'Médio',
    'common.sum': 'Soma',
    'common.price': 'Preço',
    'common.cost': 'Custo',
    'common.value': 'Valor',
    
    // 404
    'notFound.title': 'Ops! Página não encontrada',
    'notFound.returnHome': 'Voltar ao Início',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.lances': 'Lances',
    'nav.wallet': 'Wallet',
    'nav.settings': 'Settings',
    'nav.support': 'Support',
    'nav.ranking': 'Ranking',
    'nav.investments': 'Investments',
    'nav.contributions': 'Contributions',
    'nav.deposit': 'Deposit',
    'nav.withdraw': 'Withdraw',
    'nav.admin': 'Admin',
    
    // Authentication
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.forgotPassword': 'Forgot Password',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.enter': 'Enter',
    'auth.entering': 'Entering...',
    'auth.registering': 'Registering...',
    'auth.walletConnected': 'Wallet connected',
    'auth.or': 'or',
    'auth.comingSoon': 'Coming soon',
    
    // User
    'user.welcome': 'Great to have you here',
    'user.howToUse': 'How would you like to use ZK Finance?',
    'user.wantCredit': 'I want to take a loan for my business',
    'user.wantInvest': 'I want to invest',
    'user.user': 'User',
    'user.investor': 'Investor',
    'investor.contributions.title': 'Contributed Loans',
    'investor.contributions.subtitle': 'Track your investments and returns in real time',
    'user.borrower': 'Borrower',
    
    // Dashboard
    'dashboard.welcome': 'Hello',
    'dashboard.noBalance': 'You do not have an active balance yet',
    'dashboard.createNewLance': 'Create new lance',
    'dashboard.myLances': 'My Lances',
    'dashboard.createLance': 'Create Lance',
    'dashboard.filter': 'Filter',
    'dashboard.zkScore': 'ZK Score',
    'dashboard.postedLances': 'Posted Lances',
    'dashboard.totalRaised': 'Total Raised',
    'dashboard.securedCredit': 'Secured Credit to Date',
    'dashboard.goal': 'Goal',
    'dashboard.progress': 'Progress',
    'dashboard.currentAmount': 'Current Secured Credit',
    'dashboard.collaterals': 'Registered Collaterals',
    'dashboard.registerCollateral': 'Register Collateral',
    'dashboard.totalValue': 'Total Value',
    'dashboard.seeLanceDetails': 'see lance details',
    'dashboard.requestCredit': 'Request Credit',
    'dashboard.title': 'Dashboard',
    'dashboard.ranking': 'Ranking',
    'dashboard.lances': 'Lances',
    'dashboard.investmentPerformance': 'Investment Performance',
    'dashboard.recentActivities': 'Recent Activities',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.averageAPY': 'Average Total APY',
    'dashboard.totalInvested': 'Total Invested',
    'dashboard.totalReturn': 'Total Return',
    'dashboard.viewInvestmentDetails': 'View Investment Details',
    'dashboard.invested': 'Invested',
    'dashboard.return': 'Return',
    'dashboard.last7Days': 'Last 7 days',
    'dashboard.deposit': 'Deposit',
    'dashboard.withdraw': 'Withdraw',
    'dashboard.contributions': 'Contributions',
    'dashboard.approved': 'Approved',
    'dashboard.inAnalysis': 'In Analysis',
    'dashboard.notAuthorized': 'Not Authorized',
    'dashboard.backToKYC': 'Back to KYC',
    'dashboard.support': 'Support',
    'dashboard.search': 'Search',
    'dashboard.level1': 'Level 1',
    'dashboard.viewAchievements': 'View achievements',
    'dashboard.securedCreditToDate': 'Secured Credit to Date',
    'dashboard.progressGoal': 'Total Contribution Goal Progress',
    'dashboard.currentSecuredCredit': 'Current Secured Credit',
    'dashboard.value': 'Value',
    'dashboard.interest': 'Interest',
    'dashboard.expiresIn': 'Expires in',
    'dashboard.objective': 'Objective',
    
    // Wallet
    'wallet.title': 'Wallet',
    'wallet.balance': 'Balance',
    'wallet.debtBalance': 'Debt Balance',
    'wallet.totalOutstanding': 'Total outstanding amount',
    'wallet.updatedToday': 'Updated today',
    'wallet.paymentTerm': 'Payment Term',
    'wallet.remainingTime': 'Remaining time',
    'wallet.monthsRemaining': 'months remaining',
    'wallet.nextDue': 'Next Due',
    'wallet.nextInstallment': 'Next installment',
    'wallet.creditors': 'Creditors',
    'wallet.settlementAndTotals': 'Settlement and Totals',
    'wallet.immediateSettlement': 'Immediate Settlement',
    'wallet.settleAllDebt': 'Amount to settle all debt today',
    'wallet.totalFinal': 'Total Final',
    'wallet.totalAfterInterest': 'Total amount after interest at the end of contract',
    'wallet.settlementSavings': 'Settlement Savings',
    'wallet.difference': 'Difference between immediate settlement and final total',
    'wallet.requestStatement': 'Request Statement',
    'wallet.negotiateSettlement': 'Negotiate Settlement',
    'wallet.connect': 'Connect Wallet',
    'wallet.connected': 'Wallet Connected',
    'wallet.disconnect': 'Disconnect',
    'wallet.switchNetwork': 'Switch Network',
    'wallet.wrongNetwork': 'Wrong Network',
    'wallet.unsupportedNetwork': 'Unsupported Network',
    'wallet.connectWallet': 'Connect Wallet',
    'wallet.noWallet': 'No Wallet Found',
    'wallet.installWallet': 'Install Wallet',
    'wallet.polkadot': 'Polkadot',
    'wallet.evm': 'EVM',
    'wallet.substrate': 'Substrate',
    'wallet.switchToPolkadot': 'Switch to Polkadot',
    'wallet.switchToEVM': 'Switch to EVM',
    'wallet.switchNetworks': 'Change Network',
    'wallet.switching': 'Switching...',
    'wallet.sepolia': 'Sepolia',
    'wallet.sepoliaDescription': 'Loan Contract EVM',
    'wallet.voltaDescription': 'ZK Proofs ZKVerify',
    'wallet.limited': 'Limited',
    'wallet.copyAddress': 'Copy address',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.appearance': 'Appearance',
    'settings.saveChanges': 'Save Changes',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailUpdates': 'Receive updates by email',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.smsAlerts': 'Receive alerts by SMS',
    'settings.pushNotifications': 'Push Notifications',
    'settings.browserNotifications': 'Receive notifications in browser',
    'settings.marketing': 'Marketing',
    'settings.offersAndNews': 'Receive offers and news',
    'settings.darkTheme': 'Dark Theme',
    'settings.toggleTheme': 'Toggle between light and dark theme',
    
    // Support
    'support.title': 'Support',
    'support.howCanWeHelp': 'How can we help?',
    'support.findAnswers': 'Find quick answers to your questions or contact our specialized support team.',
    'support.phone': 'Phone',
    'support.24hService': '24/7 Service',
    'support.callNow': 'Call now',
    'support.email': 'Email',
    'support.response2h': 'Response within 2h',
    'support.sendEmail': 'Send email',
    'support.chat': 'Chat',
    'support.onlineService': 'Online service',
    'support.availableNow': 'Available now',
    'support.startChat': 'Start chat',
    'support.faq': 'Frequently Asked Questions',
    'support.searchFaq': 'Search frequently asked questions...',
    'support.usefulResources': 'Useful Resources',
    'support.userGuide': 'User Guide',
    'support.completeTutorial': 'Complete platform tutorial',
    'support.videoTutorials': 'Video Tutorials',
    'support.learnWithVideos': 'Learn with explanatory videos',
    'support.termsOfUse': 'Terms of Use',
    'support.platformPolicies': 'Platform policies and conditions',
    'support.mobileApp': 'Mobile App',
    'support.downloadApp': 'Download our app for Android and iOS',
    'support.access': 'Access',
    'support.subject': 'Subject',
    'support.enterSubject': 'Enter your message subject',
    'support.message': 'Message',
    'support.describeIssue': 'Describe your question or problem...',
    'support.phoneOptional': 'Phone (optional)',
    
    // KYC
    'kyc.title': 'Credit Request',
    'kyc.personalInfo': 'Personal Information',
    'kyc.idVerification': 'ID Verification',
    'kyc.selfie': 'Selfie',
    'kyc.review': 'Review',
    'kyc.creditData': 'Credit Data',
    'kyc.generalInfo': 'General Information',
    'kyc.scanCollateral': 'Scan Collateral',
    'kyc.analysis': 'Analysis',
    'kyc.step': 'Step',
    'kyc.fillPersonalInfo': 'Fill in the fields with your personal information',
    'kyc.uploadDocuments': 'Upload identification documents',
    'kyc.takeSelfie': 'Take a selfie for facial verification',
    'kyc.reviewInfo': 'Review all information before proceeding',
    'kyc.financialData': 'Provide your financial and credit data',
    'kyc.scanAssets': 'Scan or photograph your assets as collateral',
    'kyc.zkProcessing': 'ZK processing and credit score generation',
    'kyc.fullName': 'Full name',
    'kyc.birthDate': 'Birth date',
    'kyc.state': 'State',
    'kyc.city': 'City',
    'kyc.address': 'Address',
    'kyc.number': 'Number',
    'kyc.documentUpload': 'Document Upload',
    'kyc.uploadFollowing': 'Upload the following documents:',
    'kyc.rgOrCnh': 'RG or CNH (front and back)',
    'kyc.residenceProof': 'Proof of residence',
    'kyc.selectFiles': 'Select Files',
    'kyc.facialVerification': 'Facial Verification',
    'kyc.takeSelfieForVerification': 'Take a selfie for identity verification',
    'kyc.infoReview': 'Information Review',
    'kyc.notInformed': 'Not informed',
    'kyc.documentsSent': 'Documents sent',
    'kyc.selfieCaptured': 'Selfie captured',
    'kyc.infoVerified': 'Information verified',
    'kyc.monthlyIncome': 'Monthly income',
    'kyc.profession': 'Profession',
    'kyc.company': 'Company',
    'kyc.phone': 'Phone',
    'kyc.collateralsAndGuarantees': 'Collaterals and Guarantees',
    'kyc.scanOrPhoto': 'Scan or photograph your assets as collateral:',
    'kyc.vehicles': 'Vehicles',
    'kyc.properties': 'Properties',
    'kyc.electronics': 'Electronics',
    'kyc.otherValuableAssets': 'Other valuable assets',
    'kyc.scanGuarantees': 'Scan Guarantees',
    'kyc.zkAnalysisInProgress': 'ZK Proof Analysis in Progress',
    'kyc.processingData': 'We are processing your data through our ZK Finance technology. This process may take up to 24 hours.',
    'kyc.zkCreditScoreProof': 'ZK Credit Score Proof',
    'kyc.financialDataProcessed': 'Your financial and personal data is processed by AI algorithms without being stored. Only the final score is generated through zero-knowledge proof, ensuring total privacy.',
    'kyc.privacyGuaranteed': 'Privacy Guaranteed',
    'kyc.personalDataNotStored': 'Personal data is not stored',
    'kyc.processingViaZk': 'Processing via ZK algorithm',
    'kyc.scoreGeneratedByAi': 'Score generated by AI without data retention',
    'kyc.lgpdCompliance': 'LGPD Compliance',
    'kyc.processingZkProof': 'Processing ZK proof...',
    'kyc.previous': 'Previous',
    'kyc.next': 'Next',
    'kyc.finish': 'Finish',
    'kyc.backToKyc': 'Back to KYC',
    'kyc.verification': 'KYC Verification',
    
    // General
    'common.back': 'Back',
    'common.backToDashboard': 'Back to Dashboard',
    'common.home': 'Home',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.amount': 'Amount',
    'common.total': 'Total',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.failed': 'Failed',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.connected': 'Connected',
    'common.disconnected': 'Disconnected',
    'common.ready': 'Ready',
    'common.busy': 'Busy',
    'common.working': 'Working',
    'common.done': 'Done',
    'common.waiting': 'Waiting',
    'common.processing': 'Processing',
    'common.available': 'Available',
    'common.unavailable': 'Unavailable',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.on': 'On',
    'common.off': 'Off',
    'common.true': 'True',
    'common.false': 'False',
    'common.high': 'High',
    'common.low': 'Low',
    'common.medium': 'Medium',
    'common.small': 'Small',
    'common.large': 'Large',
    'common.new': 'New',
    'common.old': 'Old',
    'common.recent': 'Recent',
    'common.latest': 'Latest',
    'common.first': 'First',
    'common.last': 'Last',
    'common.best': 'Best',
    'common.worst': 'Worst',
    'common.good': 'Good',
    'common.bad': 'Bad',
    'common.maximum': 'Maximum',
    'common.minimum': 'Minimum',
    'common.average': 'Average',
    'common.sum': 'Sum',
    'common.price': 'Price',
    'common.cost': 'Cost',
    'common.value': 'Value',
    
    // 404
    'notFound.title': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('pt');

  useEffect(() => {
    // Carregar idioma salvo no localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'pt' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}; 