// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use the environment variables
const supabaseUrl = "https://tzpfzthlkuzeapftowxq.supabase.co";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

console.log('Supabase URL:', supabaseUrl);
console.log('Supabase Anon Key exists:', !!supabaseAnonKey);

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

// Create a singleton instance with a unique storage key
const STORAGE_KEY = 'entre-chain-lend-auth-v1';

// Create a singleton instance
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

export const supabase = (() => {
  if (!supabaseInstance) {
    supabaseInstance = createClient<Database>(
      supabaseUrl, 
      supabaseAnonKey,
      {
        auth: {
          autoRefreshToken: true,
          persistSession: true,
          detectSessionInUrl: true,
          flowType: 'pkce',
          storageKey: STORAGE_KEY,
          storage: {
            getItem: (key) => {
              const value = localStorage.getItem(key);
              return value ? JSON.parse(value) : null;
            },
            setItem: (key, value) => {
              localStorage.setItem(key, JSON.stringify(value));
            },
            removeItem: (key) => {
              localStorage.removeItem(key);
            }
          }
        },
        global: {
          headers: {
            'x-application-name': 'entre-chain-lend'
          }
        }
      }
    );
  }
  return supabaseInstance;
})();
